// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Like struct {
	ID        string `json:"id"`
	CreatedAt string `json:"createdAt"`
	Username  string `json:"username"`
}

type Post struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Body      string  `json:"body"`
	CreatedAt string  `json:"createdAt"`
	Username  string  `json:"username"`
	Likes     []*Like `json:"likes"`
	LikeCount int     `json:"likeCount"`
}

type RegisterInput struct {
	Username        string `json:"username"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
	Email           string `json:"email"`
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Token     string `json:"token"`
	Username  string `json:"username"`
	CreatedAt string `json:"createdAt"`
}
